name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'fabric8-analytics'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: npm
        registry-url: 'https://npm.pkg.github.com'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create .npmrc
      run: |
        echo "@trustification:registry=https://npm.pkg.github.com" >> ~/.npmrc

    - name: Install project modules
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Run unit tests
      run: npm test -- --coverage

    - name: Upload coverage to codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}